# Generated by Django 3.0.7 on 2020-06-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPhoneCatalog', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
    ]
